### ISSUE TITLE
Computer-vision documentation was broken in last update to gh-pages

### ISSUE THREAD

**Issue by benjaminwinger** [UWARG/docs#3] opened 2016-11-14 20:01 UTC
Creating an issue for this since I'm not sure if anyone noticed my comment (i.e. @scholvat).
https://github.com/UWARG/docs/commit/1963b829b1c21e3e764d32ee5e946d71cc33aedd#diff-e5b87b6ff561b3fcee6dd8059cc0574aR485

**Comment by scholvat** [comment] 2016-11-14 23:45
I realized I didn't push my commits, they are in the repo now. Links are working fine for me, I tried on Linux and Windows. Are none of the links working, or just the CV section? @benjaminwinger

**Comment by benjaminwinger** [comment] 2016-11-15 00:00
It seems to just be the links in the CV section.
I'm not sure if this is related, but among the other changes, a lot of other paths are modified by adding an additional `/` at the beginning. While that may not break the link, adding an additional `.` will.
The other interesting thing is that previously the affected links include a `./` prefix, while other similar links don't. 

Still doesn't explain why so much was changed when you built the docs though. What sort of platform were you building on? It may be that there are subtle differences depending on your environment; most of the other differences were fairly minor.

**Comment by scholvat** [comment] 2016-11-15 00:04
I'm using Windows, which is usually the cause of these issues. Do you want to try building it on linux and see if that solves it?

**Comment by benjaminwinger** [comment] 2016-11-15 02:23
It probably is the cause (and yes, the issue doesn't seem to happen when built on Linux). I've set up Jenkins to automatically build and push the docs, so now if you just push to master the website will be updated automatically needing to run `mkdocs gh-deploy`

**Comment by scholvat** [comment] 2016-11-15 13:53
Its been pushed to master, is this issue fixed now?

**Closed as completed** 2016-11-15 16:03 UTC
